# M1 T01: Pràctica amb programació numèrica NumPy

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.


## Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error


In [1]:
import numpy as np

def Stats1D(x):
    if x.ndim > 1:
        print("Error! L'array té més d'una dimensió")
    else:
        print("Mitjana:", np.mean(x))
        print("Mediana:", np.median(x))
        print("Desviació:", np.around(np.std(x),2))
        print("Mínim:", np.amin(x))
        print("Màxim:", np.amax(x))

*Passos seguits:*
- *Primer carreguem la llibreria NumPy*
- *Definim una funció, Stats1D, amb un únic paràmetre d'entrada que és el vector x*
- *Mitjançant una estructura condicional, avaluem si el vector és de dimensió 1 o superior*
- *Si el vector no és de dimensió 1, l'acció d'aquesta funció serà un print amb el missatge d'error*
- *Si el vector és de dimensió 1, l'acció d'aquesta funció serà un print de cinc estadístics descriptius*


*Alguns exemples d'aquesta funció:*

In [2]:
a = np.array([1, 2, 3, 4, 5])
Stats1D(a)

Mitjana: 3.0
Mediana: 3.0
Desviació: 1.41
Mínim: 1
Màxim: 5


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
Stats1D(b)

Error! L'array té més d'una dimensió


*Es pot veure que el vector **a** és de dimensió 1 i per tant es calculen els estadístics descriptius. I en canvi, el vector **b** és de dimensió 2 i per això surt un missatge d'error.*

## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
import numpy as np
from numpy import random

def RandomN(N):
    x = random.randint(100, size=(N,N))
    print(x)

*Passos seguits:*

- *Primer carreguem la llibreria NumPy*
- *Cridem el mòdul Random*
- *Definim una funció, RandomN, amb un únic paràmetre d'entrada que és la dimensió del quadrat (N)*
- *L'acció d'aquesta funció és un vector de NxN de nombres aletoris entre el 0 i el 100*

*Alguns exemples d'aquesta funció:*

In [5]:
RandomN(3)

[[47 13 46]
 [17 89 17]
 [70 66 26]]


In [6]:
RandomN(5)

[[11 18 71 78 25]
 [33 42 28 88 74]
 [88 38 22 80 93]
 [54 42 24 65 69]
 [80 79 69 91 20]]


## Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [7]:
import numpy as np

def TotalsFilaColumna(x):
    print("Totals per fila:",np.sum(x, axis=1))
    print("Totals per columna:",np.sum(x, axis=0))

*Passos seguits:*
- *Primer carreguem la llibreria NumPy*
- *Definim una funció, TotalsFilaColumna, amb un únic paràmetre d'entrada que és el vector x de dues dimensions*
- *L'acció d'aquesta funció són dos vectors, en un d'ells els total per fila i en l'altre els totals per columna*

*Exemple:*

In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
TotalsFilaColumna(b)

[[1 2 3]
 [4 5 6]]
Totals per fila: [ 6 15]
Totals per columna: [5 7 9]


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

*El coeficient de correlació de dues variables, **r**, es calcula com el quocient entre la covarianza i el producte de les desviacions típiques de les dues variables.*

In [9]:
def coefcorrelacio(x,y):
    r = np.cov(x,y)[0,1] / (np.std(x)*np.std(y))
    print(r)

*Quantifica el grau de relació lineal entre les dues variables. És un paràmetre que va de -1 a 1. Com més proper sigui el valor a -1 o 1 la relació és més forta*
- *Si r=0, no existeix relació lineal entre les dues variables*
- *Si r>0, la relació és positiva. Si augmenta els valors d'una de les variables, augmenta els de l'altre*
- *Si r<0, la relació és negativa. Si augmenta els valors d'una de les variables, disminueix els de l'altre*

*Exemple:*

In [10]:
alcada = np.array([1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29, 1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29, 1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29])
pes = np.array([32,33,34,30,32,35,34,32,32,35,33,35,34,30,33,34,35,32,33,33,33,34,34,31,32,34,34,31,35,34])
coefcorrelacio(alcada,pes)

0.8567457137220003
